Action mask prototype, pass existing test (+16 squashed commits) Squashed commits: [b661b29] Fix bug: action_space = Box crash [18bb1bb] fix action_mask_check bug [d69ca21] Use kwargs to pass the action_mask_ph parameter [370e031] Add default mask [10268b0] Fixed train_model action mask shape. [5ead377] Fix AttributeError: 'CategoricalProbabilityDistributionType' object has no attribute 'n_vec' [0187197] Restore ProbabilityDistributionType, overwrite proba_distribution_from_flat. [8dbb5ac] Bug fix: Environment does not return action mask, causing program crash [e06c4fe] Support action_space: Discrete [fb5ecea] support FeedForwardPolicy [9b2c2f5] Fix small amount invalid action problems [95bb5ca] Fixed neglogp is a nan error. But there will still be a small amount of invalid action. [2719987] why neglogp is nan? [1724767] Rename variable [47cc453] Override DQN action [5319f7b] Override actions